modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio"
version="${version}"
displayName="Ender IO"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, mystchonky"
description="Compact conduits, painted things and all sorts of stuff and bling."
displayURL="http://enderio.com/"
logoFile="logo.png"

[[dependencies.enderio]]
modId="minecraft"
mandatory=true
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio]]
modId="forge"
mandatory=true
versionRange="${forge_version}"
side="BOTH"

[[dependencies.enderio]]
modId="ae2"
mandatory=false
versionRange="[12.7.0,)"
side="BOTH"