modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio_base"
version="${mod_version}"
displayName="Ender IO Base"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, dphaldes"
description="The base items and materials for the Ender IO Mods."
displayURL="https://enderio.com/"
logoFile="logo.png"

[[mixins]]
config="enderiobase.mixins.json"

[[dependencies.enderio_base]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_base]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_base]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"
