modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio_machines"
version="${mod_version}"
displayName="Ender IO Machines"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, dphaldes"
description="The machines module for Ender IO"
displayURL="https://enderio.com/"
logoFile="logo.png"

[[mixins]]
config="enderio-machines.mixins.json"

[[dependencies.enderio_machines]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_machines]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_machines]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_machines]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"
