modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio_armory"
version="${mod_version}"
displayName="Ender IO Armory"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, dphaldes"
description="The Ender IO Armory module."
displayURL="https://enderio.com/"
logoFile="logo.png"

[[dependencies.enderio_armory]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_armory]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_armory]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_armory]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"
