modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio"
version="${mod_version}"
displayName="Ender IO"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, dphaldes"
description="Compact conduits, painted things and all sorts of stuff and bling. This is the monolithic jar, containing all core modules."
displayURL="https://enderio.com/"
logoFile="logo.png"

[[dependencies.enderio]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"
