modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio_conduits_modded"
version="${mod_version}"
displayName="Ender IO Modded Conduits"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, dphaldes"
description="Adding AE2, RS2 and Mekanism conduits to Ender IO."
displayURL="https://enderio.com/"
logoFile="logo.png"

[[dependencies.enderio_conduits_modded]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="enderio_conduits"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="mekanism"
type="optional"
versionRange="${mekanism_version_range}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="ae2"
type="optional"
versionRange="${ae2_version_range}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="refinedstorage"
type="optional"
versionRange="${refinedstorage_version_range}"
side="BOTH"
