name: Release Build
env:
  CI: true
  BUILD_VERSION: ${{ github.event.release.tag_name }}
  CHANGELOG: ${{ github.event.release.body }}
  PUBLISH: true

# Run when release is created on GitHub
on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Minecraft Version
        uses: madhead/read-java-properties@latest
        id: mc_version
        with:
          file: gradle.properties
          property: minecraft_version

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v3

      - name: Clean
        run: ./gradlew clean

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: enderio/build/libs/*.jar

      - name: Publish to CurseForge and Modrinth
        env:
          CURSEFORGE_TOKEN: ${{ secrets.TOKEN_CURSEFORGE }}
          MODRINTH_TOKEN: ${{ secrets.TOKEN_MODRINTH }}
        run: ./gradlew publishMod

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: enderio/build/libs/*.jar

      - name: Truncate Build Notes
        uses: 2428392/gh-truncate-string-action@v1.2.0
        id: truncatedChangelog
        with:
          stringToTruncate: ${{ github.event.release.body }}
          maxLength: 1000

      - name: Discord Notification Success
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.RELEASE_DISCORD_WEBHOOK }}
          embed-title: Ender IO ${{ github.event.release.tag_name }} Released for MC ${{ steps.mc_version.outputs.value }}
          embed-description: ${{ steps.truncatedChangelog.outputs.string }}
          avatar-url: https://raw.githubusercontent.com/Team-EnderIO/EnderIO/dev/1.20.1/doc/img/enderface.png
          username: Ender IO Releases
          embed-footer-text: ${{ github.event.release.tag_name }} for MC ${{ steps.mc_version.outputs.value }}
          embed-url: ${{ github.event.release.html_url }}
          embed-color: 5763719

      - name: Discord Notification Failure
        if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.PRIVATE_DISCORD_WEBHOOK }}
          embed-title: ${{ github.event.release.tag_name }} for MC ${{ steps.mc_version.outputs.value }} build failed
          embed-description: The release build is failing at this commit. ```${{ github.event.head_commit.message }}```
          avatar-url: https://raw.githubusercontent.com/Team-EnderIO/EnderIO/dev/1.20.1/doc/img/gray-enderface.png
          username: Ender IO Release Failure
          embed-footer-text: ${{ github.event.release.tag_name }} for MC ${{ steps.mc_version.outputs.value }}
          embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          embed-color: 15548997

      # Publish to Rover's maven last. Failure email will still be sent, but it'll still release elsewhere
      - name: Rover656 Maven Publish
        uses: gradle/gradle-build-action@v2
        env:
          RVR_MAVEN_USER: ${{ secrets.RVR_MAVEN_USER }}
          RVR_MAVEN_PASSWORD: ${{ secrets.RVR_MAVEN_PASSWORD }}
        with:
          arguments: publishAllPublicationsToRover656Repository

  updateReleaseBranch:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Minecraft Version
        uses: madhead/read-java-properties@latest
        id: mc_version
        with:
          file: gradle.properties
          property: minecraft_version

      - uses: actions/checkout@v3
        with:
          ref: release/${{ steps.mc_version.outputs.value }}
          fetch-depth: 0

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge ${{ github.event.release.tag_name }}
          git push
